// homepage
export { default as Hero } from './components/Hero'
export { default as Show } from './components/Show'
export { default as Feedback } from './components/Feedback'
export { default as SocialMedia } from './components/SocialMedia'
export { default as Home } from './pages/Home'
export {default as Layout} from './components/Layout'
export { default as Team } from './components/Team'
export { default as Trainers } from './components/Trainers'
export { default as HeadTrainer } from './components/HeadTrainer'  
export { default as Contact } from './components/Contact'  
export { default as Testimonials } from './components/Testimonials'
export { default as MembershipPlans } from './components/MembershipPlans'
export { default as Services } from './components/Services'